### PR TITLE
Fix #14: MockServer expectations abort during unrelated panic

### LINKED ISSUE #14: Avoid causing an abort in a failing test
Our current setup checks all assertions against defined `Mock`s when a `MockServer` instance is being dropped.
If a test is panicking for unrelated reason (e.g. a test assertion failed) it is possible (and sometimes quite likely) that assertions won't be satisfied either, hence when `Drop` is called on the `MockServer` while unwinding the stack another panic takes place and the whole process is aborted.

This is undesirable for several reasons:
- the whole test suite crashes, therefore it interferes with other tests in the same suite;
- no backtrace will be printed, therefore it is very messy to debug what happened.

We should leverage [panicking](https://doc.rust-lang.org/std/thread/fn.panicking.html) and avoid panicking if the current thread is panicking, limiting ourselves to printing/logging the failure.

### PR DESCRIPTION
**Pull request by Lucky1313**
I think this should solve [this issue](https://github.com/LukeMathWalker/wiremock-rs/issues/14).

I used `debug` for when the thread is already panicking, not sure if it should be a higher level log.

### CODE REVIEW

File: src/mock_server.rs [hunk 1]
```diff
@@ -239,7 +239,11 @@ impl Drop for MockServer {
     fn drop(&mut self) {
         debug!("Verify mock expectations.");
         if !run!(self.verify()) {
-            panic!("Verification failed: mock expectations have not been satisfied.");
+            if std::thread::panicking() {
+                debug!("Verification failed, but already panicking.");
```
Comment (LukeMathWalker) [inline src/mock_server.rs:243]: I would use the very same log message, I don't think we need to change it.
Debug sounds good as logging level.

Comment (Lucky1313) [reply src/mock_server.rs]: :+1:

**Comment by LukeMathWalker** [comment]
Thank you!
