### PR TITLE
Print info when expectations are not verified

### LINKED ISSUE #31: Print more info when expectations are not verified
## Problem

Right now when [expectations](https://docs.rs/wiremock/0.4.0-alpha.2/wiremock/struct.Mock.html#method.expect) are not satisfied a message similar to this one is showed:

```
thread panicked at 'Verification failed: mock expectations have not been satisfied.',
```

It would be nice to print also expected and actual number of times the server was called. They are compared here:

https://github.com/LukeMathWalker/wiremock-rs/blob/40edf7309e2d3680035a15ecf5d306a219fff99a/src/active_mock.rs#L45-L52

## Proposed solution

This method:

https://github.com/LukeMathWalker/wiremock-rs/blob/40edf7309e2d3680035a15ecf5d306a219fff99a/src/mock_set.rs#L48-L50

instead of returning `bool` should return something like:
```
enum VerificationOutcome {
    Correct,
    Incorrect(Vec<ActiveMock>),
}
``` 

where `Incorrect` contains all the `ActiveMock`s that are not verified. 

This vector should be printed in some way here:

https://github.com/LukeMathWalker/wiremock-rs/blob/40edf7309e2d3680035a15ecf5d306a219fff99a/src/mock_server.rs#L253-L261

I would like to work on this. Do you like the proposed solution?

### PR DESCRIPTION
**Pull request by MarcoIeni**
Closes #31

### CODE REVIEW

File: src/verification.rs [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+            self.expectation.error_message, self.expectation.range, self.n_matched_requests
+        )
+    }
+}
+
+pub(crate) enum VerificationOutcome {
+    /// All verifications were successful
+    Correct,
+    /// Failed verifications
+    Incorrect(Vec<Verification>),
```
Comment (LukeMathWalker) [inline src/verification.rs:33]:
```suggestion
    /// All verifications were successful
    Success,
    /// Failed verifications
    Failure(Vec<Verification>),
```

File: src/verification.rs [hunk 2]
```diff
@@ -0,0 +1,34 @@
+use crate::{active_mock::ActiveMock, mock::Expectation};
+
+#[derive(Clone)]
+pub(crate) struct Verification {
+    /// What users specified
+    pub(crate) expectation: Expectation,
+    /// Actual number of received requests that matched the specifications
```
Comment (LukeMathWalker) [inline src/verification.rs:7]:
```suggestion
    /// Actual number of received requests that matched the specification
```

File: src/mock.rs [hunk 3]
```diff
@@ -214,7 +214,24 @@ pub struct Mock {
...
     // `self.matches` should start returning `false`, regardless of the incoming request.
     pub(crate) max_n_matches: Option<u64>,
-    pub(crate) expectation: Times,
+    pub(crate) expectation: Expectation,
+}
+
+#[derive(Clone)]
+pub(crate) struct Expectation {
+    /// expected range
+    pub(crate) range: Times,
```
Comment (LukeMathWalker) [inline src/mock.rs:223]:
```suggestion
    /// The expectation is satisfied if the number of incoming requests falls within `range`.
    pub(crate) range: Times,
```

File: src/mock.rs [hunk 4]
```diff
@@ -214,7 +214,24 @@ pub struct Mock {
...
+    /// message displayed when `range` expectation is not met.
```
Comment (LukeMathWalker) [inline src/mock.rs:224]:
```suggestion
    /// Message displayed to the library user when the number of incoming requests
    /// does not fall within `range`.
```

File: src/mock.rs [hunk 5]
```diff
@@ -214,7 +214,24 @@ pub struct Mock {
...
+    pub(crate) error_message: String,
+}
+
+impl Default for Expectation {
+    fn default() -> Self {
+        Self {
+            range: Times(TimesEnum::Unbounded(RangeFull)),
+            error_message: "".to_string(),
```
Comment (LukeMathWalker) [inline src/mock.rs:232]:
```suggestion
            // No need to specify an error message because the number of requests will
            // always fall within `range` given that the range is unbounded!
            error_message: "".to_string(),
```

File: src/verification.rs [hunk 6]
```diff
@@ -0,0 +1,34 @@
+use crate::{active_mock::ActiveMock, mock::Expectation};
+
+#[derive(Clone)]
+pub(crate) struct Verification {
```
Comment (LukeMathWalker) [inline src/verification.rs:4]:
```suggestion
#[derive(Clone)]
/// A report returned by an `ActiveMock` detailing what the user expectations were and
/// how many calls were actually received since the mock was mounted on the server.
pub(crate) struct VerificationReport {
```

File: src/active_mock.rs [hunk 7]
```diff
@@ -46,10 +46,18 @@ impl ActiveMock {
     pub(crate) fn verify(&self) -> bool {
```
Comment (LukeMathWalker) [inline src/active_mock.rs:46]: This method should probably return a `VerificationReport` :thinking: 
`VerificationReport` can then have a `is_satisfied` method returning a boolean which you can use in the `filter` call.

File: src/verification.rs (hunk 6 above)
Comment (MarcoIeni) [reply src/verification.rs]: done in 0c17521
I placed the comment above `derive`. Let me know if you prefer the other way.

File: src/verification.rs (hunk 1 above)
Comment (MarcoIeni) [reply src/verification.rs]: done in 89d7d1f

File: src/active_mock.rs (hunk 7 above)
Comment (MarcoIeni) [reply src/active_mock.rs:46]: There is a performance penalty: In this way you are creating VerificationReports for all the ActiveMocks, which involves a clone:

https://github.com/MarcoIeni/wiremock-rs/blob/89d7d1fcb72805b83c567e690441bb10101a656d/src/verification.rs#L16

If you filter before, you only create VerificationReports for not verified ActiveMocks.

If you don't care about this I can do your suggested change.

Comment (LukeMathWalker) [reply src/active_mock.rs:46]: I'd say we don't care - let's optimise for readability here.

Comment (LukeMathWalker) [reply src/active_mock.rs:46]: (If you want, I'd say there should be a way to avoid the clone by using references in VerificationReport)

Comment (MarcoIeni) [reply src/active_mock.rs]: > I'd say we don't care - let's optimise for readability here.

done in a126306

> (If you want, I'd say there should be a way to avoid the clone by using references in VerificationReport)

I tried but I had problems, I will do a separate branch where I show you

Comment (MarcoIeni) [reply src/active_mock.rs]: > I tried but I had problems, I will do a separate branch where I show you

Here is it: https://github.com/MarcoIeni/wiremock-rs/tree/expect-ref

Comment (LukeMathWalker) [reply src/active_mock.rs]: Argh, true - you'd have to hold on the read permit on the lock, which is indeed undesirable. Let's clone our way out, as you did.

File: src/mock.rs [hunk 8]
```diff
@@ -323,7 +343,7 @@ impl Mock {
     ///         // We expect the mock to be called at least once.
     ///         // If that does not happen, the `MockServer` will panic on shutdown,
     ///         // causing the whole test to fail.
-    ///         .expect(1..)
+    ///         .expect(1.., "GET with 200 response should be called at least once")
```
Comment (LukeMathWalker) [inline src/mock.rs:346]:
```suggestion
    ///         .expect(1.., "We received no GET request")
```

**Comment by LukeMathWalker** [comment]
Thanks :grin: 
It will require a minor version bump, so I won't release it straight away. I have a few other improvements I want to make which might require breaking changes, so I'll group them together.
